// old_solid_version/src/store/index.tsx
import { createStore, type Store, type SetStoreFunction } from "solid-js/store";
import {
  createEffect,
  createContext,
  useContext,
  type Component,
  type ParentProps,
} from "solid-js";
import type { AppState } from "./types";
import { loadState, STORAGE_KEY } from "./start";

export type { AppState, Query, DataSource } from "./types";

// Internal context that exposes state and setState
interface StoreContextValue {
  state: Store<AppState>;
  setState: SetStoreFunction<AppState>;
}

// Create context (non-reactive)
const StoreContext = createContext<StoreContextValue>();

// Provider component (contains all reactive code)
export const StoreProvider: Component<ParentProps> = (props) => {
  // Create the store with initial state from localStorage
  const [state, setState] = createStore<AppState>(loadState());

  // Persist state to localStorage whenever it changes
  createEffect(() => {
    if (typeof window === "undefined") {
      return;
    }

    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    } catch (error) {
      console.error("Failed to save state to localStorage:", error);
    }
  });

  // Ensure activeTab always matches an open tab
  createEffect(() => {
    const activeTabValue = state.activeTab;
    const openIds = state.openQueryIds;

    if (openIds.length > 0) {
      // If there are open tabs but none are active, select the first open tab
      // Only update if activeTab is truly empty/undefined or not in the list
      if (
        !activeTabValue ||
        activeTabValue === "" ||
        !openIds.includes(activeTabValue)
      ) {
        console.log(
          "Effect: Setting activeTab to first open tab",
          openIds[0],
          "from",
          activeTabValue
        );
        setState("activeTab", openIds[0]);
      }
    } else if (activeTabValue) {
      // If there are no open tabs but activeTab is set, clear it
      console.log("Effect: Clearing activeTab (no open tabs)");
      setState("activeTab", "");
    }
  });

  return (
    <StoreContext.Provider value={{ state, setState }}>
      {props.children}
    </StoreContext.Provider>
  );
};

// Internal hook to access the store context
export function useStoreContext(): StoreContextValue {
  const context = useContext(StoreContext);
  if (!context) {
    throw new Error("useStoreContext must be used within a StoreProvider");
  }
  return context;
}

// src/store/index.tsx
import React, { createContext, useContext, useEffect, useState, useCallback } from "react";
import type { AppState } from "./types";
import { loadState, STORAGE_KEY, demoState } from "./start";

export type { AppState, Query, DataSource } from "./types";

// Internal context that exposes state and setState
interface StoreContextValue {
  state: AppState;
  setState: React.Dispatch<React.SetStateAction<AppState>>;
}

// Create context (non-reactive)
const StoreContext = createContext<StoreContextValue | null>(null);

// Provider component (contains all reactive code)
export const StoreProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // Create the store with initial state from localStorage
  const [state, setState] = useState<AppState>(loadState);

  // Persist state to localStorage whenever it changes
  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }

    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    } catch (error) {
      console.error("Failed to save state to localStorage:", error);
    }
  }, [state]);

  // Ensure activeTab always matches an open tab
  useEffect(() => {
    const activeTabValue = state.activeTab;
    const openIds = state.openQueryIds;

    if (openIds.length > 0) {
      // If there are open tabs but none are active, select the first open tab
      // Only update if activeTab is truly empty/undefined or not in the list
      if (
        !activeTabValue ||
        activeTabValue === "" ||
        !openIds.includes(activeTabValue)
      ) {
        console.log(
          "Effect: Setting activeTab to first open tab",
          openIds[0],
          "from",
          activeTabValue
        );
        setState((prev) => ({ ...prev, activeTab: openIds[0] }));
      }
    } else if (activeTabValue) {
      // If there are no open tabs but activeTab is set, clear it
      console.log("Effect: Clearing activeTab (no open tabs)");
      setState((prev) => ({ ...prev, activeTab: "" }));
    }
  }, [state.activeTab, state.openQueryIds]);

  return (
    <StoreContext.Provider value={{ state, setState }}>
      {children}
    </StoreContext.Provider>
  );
};

// Internal hook to access the store context
export function useStoreContext(): StoreContextValue {
  const context = useContext(StoreContext);
  if (!context) {
    throw new Error("useStoreContext must be used within a StoreProvider");
  }
  return context;
}

export function useResetState() {
  const { setState } = useStoreContext();
  return useCallback(() => {
    if (typeof window !== "undefined") {
      localStorage.removeItem(STORAGE_KEY);
      localStorage.removeItem("ad-hoc-lens-first-time");
      // Reload the page to show the welcome dialog again
      window.location.reload();
    } else {
      setState({ ...loadState() });
    }
  }, [setState]);
}

export function useLoadDemoState() {
  const { setState } = useStoreContext();
  return useCallback(() => {
    setState({ ...demoState });
  }, [setState]);
}
