// src/components/sidebar/AddItemDialog.tsx
import { useState } from "react";
import { Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

interface AddItemDialogProps {
  title: string;
  description: string;
  placeholder?: string;
  onAdd: () => void;
}

export function AddItemDialog({ title, description, placeholder, onAdd }: AddItemDialogProps) {
  const [isOpen, setIsOpen] = useState(false);

  const handleAdd = () => {
    onAdd();
    setIsOpen(false);
  };

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button variant="ghost" size="icon-xs">
          <Plus className="w-3 h-3" />
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{title}</DialogTitle>
          <DialogDescription>{description}</DialogDescription>
        </DialogHeader>
        <div className="py-4">
          <p className="text-sm text-muted-foreground">
            {placeholder || "Configuration will go here."}
          </p>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => setIsOpen(false)}>
            Cancel
          </Button>
          <Button onClick={handleAdd}>Add</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// old_solid_version/src/components/sidebar/AddItemDialog.tsx
import type { Component } from "solid-js";
import { createSignal } from "solid-js";
import PlusIcon from "lucide-solid/icons/plus";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

interface AddItemDialogProps {
  title: string;
  description: string;
  placeholder?: string;
  onAdd: () => void;
}

export const AddItemDialog: Component<AddItemDialogProps> = (props) => {
  const [isOpen, setIsOpen] = createSignal(false);

  const handleAdd = () => {
    props.onAdd();
    setIsOpen(false);
  };

  return (
    <Dialog open={isOpen()} onOpenChange={setIsOpen}>
      <DialogTrigger as={Button} variant="ghost" size="icon" class="h-6 w-6">
        <PlusIcon class="w-4 h-4" />
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{props.title}</DialogTitle>
          <DialogDescription>{props.description}</DialogDescription>
        </DialogHeader>
        <div class="py-4">
          <p class="text-sm text-muted-foreground">
            {props.placeholder || "Configuration will go here."}
          </p>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => setIsOpen(false)}>
            Cancel
          </Button>
          <Button onClick={handleAdd}>Add</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
