// src/components/sidebar/EditItemDialog.tsx
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

interface EditItemDialogProps {
  open: boolean;
  title: string;
  description: string;
  itemName: string;
  onOpenChange: (open: boolean) => void;
  onSave: (newName: string) => void;
}

export function EditItemDialog({
  open,
  title,
  description,
  itemName,
  onOpenChange,
  onSave,
}: EditItemDialogProps) {
  const [editedName, setEditedName] = useState(itemName);

  // Reset the edited name when dialog opens with a new item
  useEffect(() => {
    if (open) {
      setEditedName(itemName);
    }
  }, [open, itemName]);

  const handleSave = () => {
    if (editedName.trim()) {
      onSave(editedName.trim());
      onOpenChange(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSave();
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{title}</DialogTitle>
          <DialogDescription>{description}</DialogDescription>
        </DialogHeader>
        <div className="py-4">
          <Input
            value={editedName}
            onChange={(e) => setEditedName(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Enter name"
            autoFocus
          />
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button onClick={handleSave} disabled={!editedName.trim()}>
            Save
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// old_solid_version/src/components/sidebar/EditItemDialog.tsx
import type { Component } from "solid-js";
import { createSignal, createEffect } from "solid-js";
import { Button } from "@/components/ui/button";
import { TextFieldRoot, TextField } from "@/components/ui/textfield";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

interface EditItemDialogProps {
  open: boolean;
  title: string;
  description: string;
  itemName: string;
  onOpenChange: (open: boolean) => void;
  onSave: (newName: string) => void;
}

export const EditItemDialog: Component<EditItemDialogProps> = (props) => {
  const [editedName, setEditedName] = createSignal(props.itemName);

  // Reset the edited name when dialog opens with a new item
  createEffect(() => {
    if (props.open) {
      setEditedName(props.itemName);
    }
  });

  const handleSave = () => {
    if (editedName().trim()) {
      props.onSave(editedName().trim());
      props.onOpenChange(false);
    }
  };

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSave();
    }
  };

  return (
    <Dialog open={props.open} onOpenChange={props.onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{props.title}</DialogTitle>
          <DialogDescription>{props.description}</DialogDescription>
        </DialogHeader>
        <div class="py-4">
          <TextFieldRoot>
            <TextField
              value={editedName()}
              onInput={(e) => setEditedName(e.currentTarget.value)}
              onKeyDown={handleKeyDown}
              placeholder="Enter name"
              autofocus
            />
          </TextFieldRoot>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => props.onOpenChange(false)}>
            Cancel
          </Button>
          <Button onClick={handleSave} disabled={!editedName().trim()}>
            Save
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
